### ISSUE TITLE
Orkla Light cream mixer.

### ISSUE THREAD

**Issue by tomreit1** [W-P-I/20205445_Orkla#1]
staat nu in manual mode met stirrer aan, Orkla moet geholpen worden deze weer in MES control te krijgen, zodat AX weer kan bedienen.

was gisteren in Manual gezet omdat de mixer vol met product was, maar vanuit MES geen speed reference voor de stirrer werd gegeven

**Comment by tomreit1** [comment]
extra button maken, zodat een TD / admin de machine altijd in manual mode kan krijgen. 

eerst in stopped zetten(via OEM scherm als MES mode aanstaan), daarna kan via het HMI de machine in manual mode gezet worden.

**Comment by engineerWPI** [comment]
darkcream en lightcream heeft nu deze knop op oem
